# Generated by Django 5.2.7 on 2025-11-16 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_studentevent_event_attendees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calificación de Evento',
                'verbose_name_plural': 'Calificaciones de Eventos',
                'unique_together': {('user', 'event')},
            },
        ),
    ]
