# Generated by Django 5.2.7 on 2025-11-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Capacidad máxima de asistentes. Si es null, capacidad ilimitada.', null=True),
        ),
    ]
