# Generated by Django

from django.db import migrations


def create_initial_categories(apps, schema_editor):
    """
    Crea las 6 categorías predefinidas para los eventos.
    """
    Category = apps.get_model('events', 'Category')
    categories = [
        'Deportes',
        'Cultura', 
        'Académico',
        'Social',
        'Tecnología',
        'Arte'
    ]
    
    for category_name in categories:
        Category.objects.get_or_create(type=category_name)


def reverse_initial_categories(apps, schema_editor):
    """
    Revierte la creación de categorías (para hacer rollback si es necesario).
    """
    Category = apps.get_model('events', 'Category')
    categories = [
        'Deportes',
        'Cultura',
        'Académico',
        'Social',
        'Tecnología',
        'Arte'
    ]
    Category.objects.filter(type__in=categories).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_category_event_categories'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_categories,
            reverse_initial_categories
        ),
    ]