# Generated by Django 5.2.7 on 2025-12-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_notificationpreference_eventreminder'),
        ('events', '0011_remove_event_deleted_at_remove_event_deleted_by_and_more'),
    ]

    operations = [
    ]
