# Generated by Django 5.2.7 on 2025-10-12 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Use formato E.164, ej: +573001234567', regex='^\\+[1-9]\\d{1,14}$')]),
        ),
    ]
